payload:
  artifacts:
    - name: xor
      type: encoder
      args:
        - name: Key
          value: "AAAAAAAAAAAAAAAA"
    - name: sleep
      type: evasion
      args:
        - name: Delay
          value: "5"
    - name: windows/native/local/execute_fp
      type: injector
  #sgn: false #must be decommented in the code to be used
  lang: c
  type: exe
  arch: x64
  debug: true
